### ISSUE TITLE
Convert leadtime dimension from days to datetime

### ISSUE THREAD

**Issue by tom-andersson** [icenet-ai/icenet#13]
Currently, the NetCDF forecast outputs have a leadtime dimension in days (integer). While there doesn't seem to be a CF-compliance standard for this, it may be better to use a datetime for this dimension (i.e. the time that the forecast is valid for/corresponds to).

**Comment by JimCircadian** [comment]
This required more thought, as it enforces the constraint that only a single forecast can be contained within a forecast file. The leadtime must be one-dimensional in order to be compatible with the data model, as it is a dimensional coordinate along the last axis. It thus cannot change dependently based on the time axis. 

This means we can't assign two dimensional coordinates along for the leadtime coordinate, I've decided to introduce `forecast_date` that at least provides the explicit date of the forecast for easy reference

**Comment by tom-andersson** [comment]
This makes very good sense @JimCircadian, nice one
