### ISSUE TITLE
Problem with 2022 forecasts - possibly due to input data

### ISSUE THREAD

**Issue by EllieBowler** [icenet-ai/icenet#177]
Unusual predictions for 2022, possibly due to corrupt input data. 

Investigating/ plotting input data to explore - anomolous tos_anom already identified. 

@rchan26 @JimCircadian

**Comment by JimCircadian** [comment]
There's some masking issue that's been introduced, likely because the SIC mask is being applied to the data during regridding. Data analysis showed the problem up (each processed year encompasses the next year...)

```
From source data
  2019: max 308.3791809082031 min 0.0
  2020: max 308.8356018066406 min 0.0
  2021: max 308.8074645996094 min 0.0
  2022: max 308.81201171875 min 0.0

From processed data
  processed/ellie_2019_north/era5/north/tos/tos_anom.nc
  2019: max 0.8716910481452942 min 0.18290071189403534
  2020: max 0.9913584589958191 min 0.12792715430259705

  processed/ellie_2020_north/era5/north/tos/tos_anom.nc
  2020: max 0.9913584589958191 min 0.12792715430259705
  2021: max 0.8968613743782043 min -7.399646282196045

  processed/ellie_2021_north/era5/north/tos/tos_anom.nc
  2021: max 0.8968613743782043 min -7.399646282196045
  2022: max 8.40521240234375 min -7.399646282196045

  processed/ellie_2022_north/era5/north/tos/tos_anom.nc
  2022: max 8.40521240234375 min -7.399646282196045
  2023: max 7.962932109832764 min -7.317650318145752
```

The ranges change between 2021 and 2022, perhaps they were downloaded at different times. Re-downloading these years:

2021
![image](https://github.com/icenet-ai/icenet/assets/731727/dce7d84d-c72c-47c0-8fd5-74f669d9f9d0)

2022
![image](https://github.com/icenet-ai/icenet/assets/731727/c4480802-ca34-4795-8d3e-f973948ae460)

CC @rchan26 @tom-andersson

**Comment by JimCircadian** [comment]
Happy days, 2021 reprocessed without the SIC land mask is fine: 

![image](https://github.com/icenet-ai/icenet/assets/731727/3d08d976-3090-410e-b576-00d54f4fa3fc)

**Comment by tom-andersson** [comment]
Nice one @JimCircadian!

Does the line below take care of the extreme values over land in the `tos_abs` case? These values would get silently subtracted out during the anomaly computation and wouldn't be visible in the screenshot above, hence thought worth checking in case we want to use `tos_abs` in future.
https://github.com/icenet-ai/icenet/blob/e96be724995a5f071911808e1ba6739c17d6954c/icenet/data/interfaces/cds.py#L253C1-L254C1

**Comment by JimCircadian** [comment]
![Screenshot_2023-08-03_13-27-34](https://github.com/icenet-ai/icenet/assets/731727/c68598f2-3328-4acc-93b9-54bf1e67a6b8)

Fixed the input channels

**Comment by JimCircadian** [comment]
@tom-andersson The other masking should take care of those values, but I'll have a check with tos_abs now 👍🏼
