### ISSUE TITLE
Additional validation from the icenet paper repository

### ISSUE THREAD

**Issue by ots22** [icenet-ai/icenet#95]
Are there any validation outputs (plots, other figures, or processed data for the purpose of validation) to capture in icenet from https://github.com/tom-andersson/icenet-paper?

@tom-andersson

**Comment by JimCircadian** [comment]
Looking through the [SIE error](https://github.com/tom-andersson/icenet-paper/blob/main/icenet/analyse_heldout_predictions.py) and the [uncertainty quantification](https://github.com/tom-andersson/icenet-paper/blob/main/icenet/analyse_uncertainty.py) in the repo and turning these into new commands that can be run / plotted for forecasts automatically is definitely of *significant value*. Happy to discuss, as this should be an interesting porting job, with the data requirements already having been fulfilled: I just haven't had the time to porting these yet!

**Comment by tom-andersson** [comment]
[Here](https://github.com/tom-andersson/icenet2/blob/main/icenet2/analyse_forecasts.py) is a script I used to validate IceNet v2 from my old research codebase, which was used as a starting point for refactoring into `icenet`. Note, the script lies in a private repo so only invited collaborators can access it. 

The script itself is very inflexible because it assumes a lot of specific features of the codebase I was doing my research in. However, hopefully you'll be able to spot the generic functionality within all that. For example, [this snippet](https://github.com/tom-andersson/icenet2/blob/4ca0f1300fbd82335d8bb000c85b1e71855630fa/icenet2/analyse_forecasts.py#L266-L365) could quite readily be converted into a function with forecast and ground truth `xarray` object arguments.

@JimCircadian and I used `distributed` here to validate huge forecast NetCDFs in a parallelised fashion, which could come in handy here.

**Comment by tom-andersson** [comment]
Apologies for the lack of a docstring in the private script above, but you can use the docstring from [the analogous script in the `icenet-paper` repo](https://github.com/tom-andersson/icenet-paper/blob/e4c2a0ab1c431d5449e2332917ac8f724245fa39/icenet/analyse_heldout_predictions.py#L16-L52) for a gist.

cc @rchan26 @ots22 @JimCircadian

**Comment by JimCircadian** [comment]
Will #112 be the conclusion of this issue @rchan26? Going to wrap up the issues on the 0.2.2 milestone and release start of next week I think!

**Comment by rchan26** [comment]
@JimCircadian yes I think so!
